org: songneilsong
app: extraartinary
service: website

provider: aws

functions:
  contactForm:
    handler: backend/contactForm.handler
    events:
      - http:
          path: post/contactform
          method: post
          cors: true

plugins:
  - serverless-finch

custom:
  client:
    bucketName: extraartinary.com
    distributionFolder: frontend
    errorDocument: index.html
